In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
matrix.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [4]:
matrix1 = np.array([[2,1,7,4],[5,6,7,3],[9,8,2,12],[11,14,15,15]])
matrix1

array([[ 2,  1,  7,  4],
       [ 5,  6,  7,  3],
       [ 9,  8,  2, 12],
       [11, 14, 15, 15]])

In [5]:
matrix1.transpose()

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

In [6]:
matrix2 = np.array([[3,7,8,3,6],[2,5,9,4,13]])
matrix2

array([[ 3,  7,  8,  3,  6],
       [ 2,  5,  9,  4, 13]])

In [7]:
matrix2.transpose()

array([[ 3,  2],
       [ 7,  5],
       [ 8,  9],
       [ 3,  4],
       [ 6, 13]])

In [2]:
X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]


for i in range(len(X)):
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]
