In [1]:
from sympy import *
import numpy
x,y,z=symbols('x, y, z')

In [2]:
X1 = Matrix([[-1,7,-34],[8,8,-48]])
X1

Matrix([
[-1, 7, -34],
[ 8, 8, -48]])

In [3]:
linsolve(X1,[x,y])

{(-1, -5)}

In [4]:
X2 = Matrix([[4,-7,-4],[3,-4,-3]])
linsolve(X2,[x,y])

{(-1, 0)}

In [5]:
X3 = Matrix([[8,-4,64],[-3,3,-21]])
linsolve(X3,[x,y])

{(9, 2)}

In [6]:
X4 = Matrix([[5,7,-5,-47],[0,-2,2,10],[-4,-8,-7,63]])
linsolve(X4,[x,y,z])

{(-2, -6, -1)}

In [7]:
x1 = Matrix([[-1,7],[8,8]])
a1=Matrix([-1,-5])
x1*a1

Matrix([
[-34],
[-48]])

In [8]:
x2 = Matrix([[4,-7],[3,-4]])
a2=Matrix([-1,0])
x2*a2

Matrix([
[-4],
[-3]])

In [9]:
x3 = Matrix([[8,-4],[-3,3]])
a3=Matrix([9,2])
x3*a3

Matrix([
[ 64],
[-21]])

In [10]:
x4 = Matrix([[5,7,-5],[0,-2,2],[-4,-8,-7]])
a4=Matrix([-2,-6,-1])
x4*a4

Matrix([
[-47],
[ 10],
[ 63]])

In [44]:
MSE = 1/6 * ((5*x + 7*y - 5*z + 47)**2 + 
             (-2*y + 2*z - 10)**2 + 
             (-4*x - 8*y - 7*z - 63)**2 + 
             (x + y + 2*z + 1)**2 + 
             (2*x - y + 2*z + 4)**2 + 
             (4*x + y + 4*z + 2)**2)
MSE

0.166666666666667*(-2*y + 2*z - 10)**2 + 0.166666666666667*(-4*x - 8*y - 7*z - 63)**2 + 0.166666666666667*(x + y + 2*z + 1)**2 + 0.166666666666667*(2*x - y + 2*z + 4)**2 + 0.166666666666667*(4*x + y + 4*z + 2)**2 + 0.166666666666667*(5*x + 7*y - 5*z + 47)**2

In [45]:
MSE.subs({x: 0, y: 0, z: 0})

1049.83333333333

In [46]:
MSE1 = diff(MSE, x)
MSE2 = diff(MSE, y)
MSE3 = diff(MSE, z)

In [47]:
step = 0.01
point = numpy.array([0,0,0])
grad = numpy.array([MSE1.subs({x:point[0], y:point[1], z:point[2]}),
                    MSE2.subs({x:point[0], y:point[1], z:point[2]}),
                    MSE3.subs({x:point[0], y:point[1], z:point[2]})])
grad

array([168.000000000000, 284.000000000000, 68.0000000000000], dtype=object)

In [48]:
next_point = point - step*grad
next_point

array([-1.68000000000000, -2.84000000000000, -0.680000000000000],
      dtype=object)

In [49]:
res = MSE.subs({x:next_point[0], y:next_point[1],z:next_point[2]})
counter = 1
res

247.497333333333

In [50]:
while res > 55:
    point = next_point
    grad = numpy.array([MSE1.subs({x:point[0], y:point[1], z:point[2]}),
                        MSE2.subs({x:point[0], y:point[1], z:point[2]}), 
                        MSE3.subs({x:point[0], y:point[1], z:point[2]})])
    next_point = point - step*grad
    res = MSE.subs({x:next_point[0], y:next_point[1],z:next_point[2]})
    counter+=1
res, counter, next_point

(54.3188045027199,
 7,
 array([-2.23893438867603, -5.49162915212318, -0.412953715575168],
       dtype=object))